# Uncomment the next line to define a global platform for your project
# platform :ios, ‚9.3‘

target 'PandaFit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'

  # Pods for PandaFit

end

target 'PandaFit WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PandaFit WatchKit App

end

target 'PandaFit WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'

  # Pods for PandaFit WatchKit Extension

end
